service: geolocation-api

provider:
  name: aws
  runtime: nodejs8.10

  stage: dev
  region: us-east-1

functions:
  fetchLocationData:
    handler: handler.fetchLocationData
    events:
      - http:
          path: location
          method: get
          cors: true